In [1]:
import torch

In [2]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
# tensor operation
y = x+2

In [4]:
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
print(y.grad_fn)

In [6]:
z = y*y*3
out = z.mean()

In [7]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [8]:
a = torch.rand(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)

False


In [9]:
a.requires_grad_(True)

tensor([[-3.0240, -0.5646],
        [-0.7582, -1.2491]], requires_grad=True)

In [10]:
b = (a*a).sum()
print(b.grad_fn)

In [11]:
out.backward()

In [13]:
print (x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [19]:
# vector-Jacobian product

x = torch.randn(3, requires_grad=True)
y = x*2
while y.data.norm()<1000:
    y = y*2
print(y)

tensor([ 374.7712, -894.6950, -514.2408], grad_fn=<MulBackward0>)


In [20]:
v = torch.tensor([0.1,1.0,0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [21]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


In [23]:
y = x.detach()
print(y.requires_grad)

print(x.eq(y).all())


False
tensor(True)
